export interface Types {
    id: number,
    personid: number,
    firstname: string,
    lastname: string,
    dateofbirth: Date,
    birthfacility: string,
    otherdefectstext: string,
    diagcode: string,
    sourcedischargedata: boolean,
    sourcebirthcertificate: boolean,
    sourcecasereport: boolean,
    sourcedeathcertificate: boolean,
    nocase: boolean,
    abstractor: string,
    assigningdate: Date,
    Edit: string,
    Open: string,
}